name: stegaimg
description: A Flutter project for image steganography.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# To see which dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Use with ImagePicker() for choosing image
  image_picker: ^0.8.5+3

  # For encryption and decryption
  encrypt: ^5.0.1

  # For image
  image: ^3.2.0

  # For permissions
  permission_handler: ^9.2.0

  # For Saving image
  path_provider: ^2.0.10

  # For generating app logo icons
  flutter_launcher_icons: ^0.9.2

# Generating App Logo Icons using flutter_launcher_icons
# After setting up the below configuration, all that is left to do is run the package.
# Run below commands inside stegaimg folder only.
# Step 1: flutter pub get
# Step 2: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/StegaImg.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is included with your application,
  # so that you can use the icons in the material Icons class.
  uses-material-design: true

  fonts:
    - family: JosefinSans
      fonts:
        - asset: "assets/fonts/Josefin_Sans/JosefinSans-Regular.ttf"

  assets:
    - "assets/gifs/loading.gif"
    - "assets/gifs/error.gif"
    - "assets/gifs/noImg.gif"

